### ISSUE TITLE
Generic types

### ISSUE THREAD

**Issue by TmLev** [suchipi/safety-match#12]
Is it possible to define generic type as one of the variants?

My attempt:

```ts
const LoadState = makeTaggedUnion({
  Unstarted: none,
  Loading: (percentLoaded: number) => percentLoaded,
  Loaded: <T>(response: T) => response,
  Error: (error: Error) => error,
});

type LoadState<T> = MemberType<typeof LoadState> // Doesn't really work since `LoadState` is not generic.
```

**Comment by suchipi** [comment]
Due to limitations in TypeScript, you can't really do generics with these values, since they're not functions or classes. But, you can do [something pretty close](https://github.com/suchipi/safety-match/blob/be271e876c299f8c7ff62d3370071b0ff09c49f5/src/index.test.ts#L125-L161) by using a function to create tagged unions, like so:

```ts
function makeMaybe<T>() {
  return makeTaggedUnion({
    Some: (data: T) => ({ data }),
    None: none,
  });
}

const Maybe_String = makeMaybe<string>();
const Maybe_Number = makeMaybe<number>();

const data1 = Maybe_String.Some("hi");
const data2 = Maybe_Number.Some(456);

data1.match({
  Some: ({ data }) => data, // data is string here
  None: () => null,
});

data2.match({
  Some: ({ data }) => data, // data is number here
  None: () => null,
});
```

It's not as nice, but it works.

**Comment by TmLev** [comment]
Thanks!

Unfortunately, this approach cannot be used in context where, for example, type of `Maybe.Some` is controlled by caller, since it would require creating required type on each invocation, but it works for simple cases.

**Comment by suchipi** [comment]
Here's a solution that allows `Maybe.Some` to still be controlled by the caller: https://github.com/suchipi/safety-match/issues/15#issuecomment-1384721329
